name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - master

jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/Doc2Markdown" >> $GITHUB_ENV

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential unixodbc-dev

      - name: Install Java 17
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          java -version

      - name: Install SonarScanner
        run: |
          curl -L "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip" -o sonar-scanner-linux.zip
          unzip sonar-scanner-linux.zip -d /opt
          sudo ln -s /opt/sonar-scanner-6.2.1.4610-linux-x64/bin/sonar-scanner /usr/local/bin/sonar-scanner
          sonar-scanner --version

      # Run SonarCloud Analysis (Master Branch)
      - name: Run SonarCloud Analysis (Master Branch)
        if: github.ref == 'refs/heads/master'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd Doc2Markdown/app
          sonar-scanner \
            -Dsonar.projectKey=jaimeflores_doc2markdown \
            -Dsonar.organization=jaimeflores \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.python.coverage.reportPaths=report_coverage/coverage.xml \
            -Dsonar.branch.name=master

       # Check if htmlcov exists
      - name: Check if htmlcov exists
        run: |
          if [ -d "Doc2Markdown/report_coverage/htmlcov" ]; then
            echo "htmlcov directory exists."
          else
            echo "htmlcov directory does not exist. Exiting."
            exit 1
          fi

      # Copiar htmlcov a un lugar temporal antes de cambiar de rama
      - name: Backup htmlcov folder
        run: |
          mkdir backup_htmlcov
          cp -r Doc2Markdown/report_coverage/htmlcov/* backup_htmlcov/

      # Cambiar a gh-pages
      - name: Publish report to GitHub Pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

          # Ahora traemos los archivos que habíamos respaldado
          mkdir -p htmlcov
          cp -r ../backup_htmlcov/* htmlcov/

          git add htmlcov
          git commit -m "Publishing SonarCloud coverage report"
          git push origin gh-pages
