name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - master

jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/Doc2Markdown" >> $GITHUB_ENV

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential unixodbc-dev

      - name: Install Java 17
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          java -version

      - name: Install SonarScanner
        run: |
          curl -L "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip" -o sonar-scanner-linux.zip
          unzip sonar-scanner-linux.zip -d /opt
          sudo ln -s /opt/sonar-scanner-6.2.1.4610-linux-x64/bin/sonar-scanner /usr/local/bin/sonar-scanner
          sonar-scanner --version

      # Run SonarCloud Analysis (Master Branch)
      - name: Run SonarCloud Analysis (Master Branch)
        if: github.ref == 'refs/heads/master'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd Doc2Markdown/app
          sonar-scanner \
            -Dsonar.projectKey=jaimeflores_doc2markdown \
            -Dsonar.organization=jaimeflores \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.python.coverage.reportPaths=Doc2Markdown/report_coverage/coverage.xml \
            -Dsonar.branch.name=master

      # Create Reports folder and move htmlcov
      - name: Create Reports folder
        run: |
          mkdir -p Doc2Markdown/Reportes
          mv Doc2Markdown/report_coverage/htmlcov/ Doc2Markdown/Reportes/

      # Check if htmlcov exists
      - name: Check if htmlcov exists
        run: |
          if [ -d "Doc2Markdown/Reportes/htmlcov" ]; then
            echo "htmlcov directory exists."
          else
            echo "htmlcov directory does not exist. Exiting."
            exit 1
          fi

      # Remove .gitignore from htmlcov
      - name: Remove .gitignore from htmlcov
        run: |
          if [ -f "Doc2Markdown/Reportes/htmlcov/.gitignore" ]; then
            rm -f Doc2Markdown/Reportes/htmlcov/.gitignore
          fi

      # Configure Git for GitHub Pages
      - name: Configure Git for GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Commit local changes
      - name: Commit local changes
        run: |
          git add . 
          git commit -m "Saving analysis reports" || echo "No changes to commit"

      # Publish report to GitHub Pages
      - name: Publish report to GitHub Pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          mkdir -p htmlcov
          cp -r Doc2Markdown/Reportes/htmlcov/* htmlcov/
          git add htmlcov
          git commit -m "Publishing SonarCloud coverage report and htmlcov"
          git push origin gh-pages